version: '3'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jobs:/var/jenkins_home/jobs
    networks:
      - jenkins-net

  jenkins-agent:
    image: jenkins/inbound-agent:latest
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_SECRET=jenkins-secret
      - JENKINS_AGENT_NAME=agent1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins-master
    networks:
      - jenkins-net

networks:
  jenkins-net:
    driver: bridge

volumes:
  jenkins_home:
