version: '3'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jobs:/var/jenkins_home/jobs
    networks:
      - jenkins-net

  jenkins-agent:
    image: jenkins/inbound-agent:latest
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_SECRET=your_actual_secret_here
      - JENKINS_AGENT_NAME=your_agent_name_here
    volumes:
      - jenkins-agent-root:/home/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins-master
    networks:
      - jenkins-net

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    ports:
      - "8081:8081"
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    networks:
      - jenkins-net

networks:
  jenkins-net:
    driver: bridge

volumes:
  jenkins_home:
  jenkins-agent-root:
  artifactory_data:
