version: '3'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jobs:/var/jenkins_home/jobs

volumes:
  jenkins_home:
