version: '3'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./:/var/my_local_repo  # Map the current directory to /var/my_local_repo inside the container
    networks:
      - dev_network

  jenkins-agent:
    image: jenkins/agent
    networks:
      - dev_network

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss
    ports:
      - "8081:8081"
    networks:
      - dev_network

networks:
  dev_network:
volumes:
  jenkins_home:
